name: Build LKM for KernelSU
on:
  workflow_call:
    inputs:
      upload:
        required: true
        type: boolean
        default: true
        description: "Whether to upload to branch"
  workflow_dispatch:
    inputs:
      upload:
        required: true
        type: boolean
        default: true
        description: "Whether to upload to branch"
jobs:
  build-lkm:
    strategy:
      matrix:
        kmi:
          - "android12-5.10"
          - "android13-5.10"
          - "android13-5.15"
          - "android14-5.15"
          - "android14-6.1"
          - "android15-6.6"
          - "android16-6.12"
    # uses: ./.github/workflows/gki-kernel-mock.yml when debugging
    uses: ./.github/workflows/ddk-lkm.yml
    with:
      kmi: ${{ matrix.kmi }}
      ddk_release: '20251104'

  push-to-branch:
    needs: [build-lkm]
    runs-on: ubuntu-latest
    if: ${{ inputs.upload }}
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin/
          merge-multiple: true
      - name: Push to Branch LKM 
        uses: peaceiris/actions-gh-pages@v4 
        with:  
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: ./bin 
          publish_branch: lkm 
          user_name: "github-actions[bot]" 
          user_email: 'github-actions[bot]@users.noreply.github.com' 
          disable_nojekyll: true 
          commit_message: "Upload LKM from"
